openlineage_compatibility_test:
  target: postgres
  outputs:
    postgres:
      type: postgres
      host: "{{ env_var('DBT_POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('DBT_POSTGRES_PORT', '5432') | as_number }}"
      user: "{{ env_var('DBT_POSTGRES_USER', 'testuser') }}"
      password: "{{ env_var('DBT_POSTGRES_PASSWORD', 'testpass') }}"
      dbname: "{{ env_var('DBT_POSTGRES_DB', 'dbt_test') }}"
      schema: "{{ env_var('DBT_POSTGRES_SCHEMA', 'main') }}"
      threads: 4