version: 2

sources:
  - name: raw_data
    description: Raw CSV data files
    schema: main
    tables:
      - name: raw_customers
        description: Raw customer data
        columns:
          - name: customer_id
            description: Unique customer identifier
            tests:
              - unique
              - not_null
          - name: email
            description: Customer email address
            tests:
              - unique
              - not_null

      - name: raw_orders
        description: Raw order data
        columns:
          - name: order_id
            description: Unique order identifier
            tests:
              - unique
              - not_null
          - name: customer_id
            description: Foreign key to customers
            tests:
              - not_null

models:
  - name: stg_customers
    description: Cleaned and standardized customer data
    columns:
      - name: customer_id
        description: Unique customer identifier
        tests:
          - unique
          - not_null

  - name: stg_orders
    description: Cleaned order data excluding cancelled orders
    columns:
      - name: order_id
        description: Unique order identifier
        tests:
          - unique
          - not_null
      - name: customer_id
        description: Foreign key to customers
        tests:
          - not_null

  - name: customer_analytics
    description: Customer analytics with aggregated metrics
    columns:
      - name: customer_id
        description: Unique customer identifier
        tests:
          - unique
          - not_null
      - name: total_revenue
        description: Total completed revenue per customer
        tests:
          - not_null