name: Scenario Validation

on:
  workflow_call:
    inputs:
      release:
        description: "release tag of OpenLineage to use"
        type: string
      get-circleci-artifacts:
        description: "Should the artifact be downloaded from maven repo or circleci"
        type: boolean

jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validation
        uses: ./.github/actions/run_event_validation
        with:
          component: 'scenarios'
          version: ${{ inputs.release }}
          target-path: 'scenarios-report.json'

      - uses: actions/upload-artifact@v4
        with:
          name: scenarios-report
          path: reports/scenarios-report.json
          retention-days: 1
