name: Collect Reports
# TODO update from placeholder to actual functionality
on:
  workflow_call:
    secrets:
      gcpKey:
        required: true

jobs:
  collect-reports:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create report directory
        run: mkdir -p reports/

      - uses: actions/download-artifact@v4
        with:
          name: dataplex-report
          path: reports/

      - name: Run task for Collect Reports
        id: collect-reports
        run: cat reports/dataplex-report.json
