name: Collect Reports
# TODO update from placeholder to actual functionality
on:
  workflow_call:
    secrets:
      gcpKey:
        required: true
    inputs:
      exec_time:
        type: string
        description: "Workflow execution time"

jobs:
  collect-and-compare-reports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: refs/heads/main

      - uses: actions/upload-artifact@v4
        with:
          name: last-report
          path: generated-files/report.json
          retention-days: 1

      - uses: actions/checkout@v4

      - name: Create report.json directory
        run: mkdir -p reports/

      - uses: actions/download-artifact@v4
        with:
          path: reports/
          merge-multiple: true

      - name: Run task for Collect Reports
        id: collect-and-merge-reports
        run: python scripts/compare_and_merge_reports.py --report_base_dir=./reports/

      - uses: actions/upload-artifact@v4
        with:
          name: updated-report
          path: reports/updated-report.json
          retention-days: 1

      - uses: actions/upload-artifact@v4
        with:
          name: retention-failures-report
          path: reports/retention-failures-report.json
          retention-days: 1
