name: Scenarios
# TODO update from placeholder to actual functionality
on: workflow_call
# TODO - for now if there is any change in scenarios, run all consumers (no filtering)
jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run task for Scenarios
        run: echo "Running task for Scenarios"