name: Check Changed Directories and Trigger Sub-workflow



on: push
# actual trigger for daily run of workflow
#on:
#  schedule:
#    - cron: "0 3 * * *"


permissions:
  id-token: write
  contents: write  # Add any other permissions as needed

jobs:
  initialize_workflow:
    runs-on: ubuntu-latest
    outputs:
#      artifact_suffix: ${branch}-${{ github.run_id }}
      exec_time: ${{ steps.exec_time.outputs.time }}
      run_dataplex: ${{ steps.select-components.outputs.dataplex }}
      run_spark: ${{ steps.select-components.outputs.spark }}
      spark_version: ${{ steps.select-components.outputs.spark_version }}
      run_spark_dataproc: ${{ steps.select-components.outputs.spark_dataproc }}
      spark_dataproc_version: ${{ steps.select-components.outputs.spark_dataproc_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get workflow execution time
        id: exec_time
        run: echo "time=$(date +%Y%m%dT%H%M%S)" >> $GITHUB_OUTPUT

      - name: Select components to run
        id: select-components
        run: |
          python component_versions/check_for_new_versions.py
          cat component_versions/list >> $GITHUB_OUTPUT

  dataplex:
    needs: initialize_workflow
    if: ${{ needs.initialize_workflow.outputs.run_dataplex == 'true' }}
    uses: ./.github/workflows/consumer-dataplex.yml
#    with:
#      artifact_suffix: ${{ needs.initialize_workflow.outputs.artifact_suffix }}
    secrets:
      gcpKey: ${{ secrets.GCP_SA_KEY }}

  scenarios:
    needs: initialize_workflow
    if: ${{ needs.initialize_workflow.outputs.run_scenarios == 'true' }}
    uses: ./.github/workflows/consumer-scenarios.yml

  spark:
    needs: initialize_workflow
    if: ${{ needs.initialize_workflow.outputs.run_spark == 'true' }}
    uses: ./.github/workflows/producer-spark.yml
    with:
      spark_version: ${{ needs.initialize_workflow.outputs.spark_version }}

  spark-dataproc:
    needs: initialize_workflow
    if: ${{ needs.initialize_workflow.outputs.run_spark_dataproc == 'true' }}
    uses: ./.github/workflows/producer-spark-dataproc.yml

  collect-reports:
    needs:
      - initialize_workflow
      - dataplex
      - scenarios
      - spark
      - spark-dataproc
    if: ${{ !failure() }}
    uses: ./.github/workflows/collect-reports.yml
    secrets:
      gcpKey: ${{ secrets.GCP_SA_KEY }}
    with:
      ${{ needs.initialize_workflow.outputs.exec_time }}

  notify-maintainers:
    needs: collect-reports
    uses: ./.github/workflows/notify-maintainers.yml

  create-version-change-pr:
    needs: notify-maintainers
    uses: ./.github/workflows/create-version-change-pr.yml