name: Generate compatibility tables

on:
  workflow_call:
    
jobs:
  generate-compatibility-tables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: updated-report
          path: reports/
          merge-multiple: true

      - name: Install dependencies
        run: |
          pip install py-markdown-table 

      - name: Run task for Collect Reports
        id: collect-and-merge-reports
        run: |
          python scripts/generate_compatibility_tables.py \
          --report=reports/updated-report.json \
          --target=reports/updated-compatibility-tables

      - uses: actions/upload-artifact@v4
        with:
          name: updated-compatibility-tables
          path: reports/updated-compatibility-tables
          retention-days: 1