name: Notify Maintainers
# TODO update from placeholder to actual functionality
on:
  workflow_call:
#    inputs:
#      failure_report_path:
#        type: string
#        description: ""
jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: retention-failures-report
          path: reports/
          merge-multiple: true

      - name: Run task for Collect Reports
        id: collect-and-merge-reports
        run: |
          python scripts/compare_and_merge_reports.py \
          --failure_path=reports/retention-failures-report.json \
          --issue_path=generated-files/issue.md

      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: An example issue
          content-filepath: generated-files/issue.md
          labels: |
            report
            automated issue