name: Spark Dataplex
# TODO update from placeholder to actual functionality
on: workflow_call

jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: get latest OL tag
        id: latest_ol_tag
        run: echo "ol_version=$(curl https://api.github.com/repos/OpenLineage/OpenLineage/releases/latest -s | jq .tag_name -r)" >> $GITHUB_OUTPUT

      - name: get latest OL spec
        uses: actions/checkout@v4
        with:
          repository: Openlineage/OpenLineage
          ref: ${{ steps.latest_ol_tag.outputs.ol_version }}
          path: .
          sparse-checkout: spec

      - name: Run task for Spark Dataplex
        run: |
          python scripts/validate_schemas.py --event_base_dir=events --spec_dirs=spec/,spec/facets/,spec/registry/gcp/dataproc/facets,spec/registry/gcp/lineage/facets/GcpLineageJobFacet.json --component=Spark