name: Spark
# TODO update from placeholder to actual functionality
on: workflow_call

jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run task for Spark
        run: echo "Running task for Spark"