name: Spark Dataplex
# TODO update from placeholder to actual functionality
on: workflow_call

jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: get latest OL tag
        id: latest_ol_tag
        run: echo "ol_version=$(curl https://api.github.com/repos/OpenLineage/OpenLineage/releases/latest -s | jq .tag_name -r)" >> $GITHUB_OUTPUT

      - name: get latest OL spec
        uses: actions/checkout@v4
        with:
          repository: Openlineage/OpenLineage
          ref: ${{ steps.latest_ol_tag.outputs.ol_version }}
          path: .spec/
          sparse-checkout: spec

      - name: list files
        run: |
          echo "BASE LEVEL FILES\n"
          ls 
          echo "FILES IN spec/ \n"
          ls spec
          echo "END \n"

      - name: Run task for Spark Dataplex
        run: |
          pip install jsonschema
          python scripts/validate_schemas.py --event_base_dir=events --spec_dirs=spec/spec/,spec/spec/facets/,spec/spec/registry/gcp/dataproc/facets,spec/spec/registry/gcp/lineage/facets/GcpLineageJobFacet.json --component=Spark