name: Python application

on:
  push:
    branches: [ 'workflow-first-version' ]
  pull_request:
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  dataplex:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run python script
      run: |
        python ./consumer/consumers/Dataplex/validator/test.py
    - name: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    - name: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: 'result.json'
        destination: 'tnazarew-ol-test/reports'

