name: Pull Request to test repo

on:
  pull_request:
  push:
    paths:
      - 'consumer/consumers/Dataplex/**'
      - 'consumer/scenarios/**'
      - 'producer/Spark/**'
      - 'producer/Spark-Dataproc/**'

permissions:
  id-token: write
  contents: read  # Add any other permissions as needed

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      exec_time: ${{ steps.exec_time.outputs.time }}
      run_dataplex: ${{ steps.changed-files.outputs.dataplex_any_changed }}
      run_scenarios: ${{ steps.changed-files.outputs.scenarios_any_changed }}
      run_spark: ${{ steps.changed-files.outputs.spark_any_changed }}
      run_spark_dataproc: ${{ steps.changed-files.outputs.spark_dataproc_any_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get workflow execution time
        id: exec_time
        run: echo "time=$(date +%Y%m%dT%H%M%S)" >> $GITHUB_OUTPUT

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files_yaml: |
            scenarios:
              - consumer/scenarios/**
            dataplex:
              - consumer/consumers/Dataplex/**
            spark:
              - producer/spark/**
            spark_dataproc:
              - producer/spark-dataproc/**

  dataplex:
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.run_dataplex == 'true' }}
    uses: ./.github/workflows/consumer-dataplex.yml
    secrets:
      gcpKey: ${{ secrets.GCP_SA_KEY }}

  scenarios:
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.run_scenarios == 'true' }}
    uses: ./.github/workflows/consumer-scenarios.yml

  spark:
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.run_spark == 'true' }}
    uses: ./.github/workflows/producer-spark.yml

  spark-dataproc:
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.run_spark_dataproc == 'true' }}
    uses: ./.github/workflows/producer-spark-dataproc.yml

  collect-reports:
    needs:
      - dataplex
      - scenarios
      - spark
      - spark-dataproc
    if: ${{ !failure() }}
    uses: ./.github/workflows/collect-and-compare-reports.yml
    secrets:
      gcpKey: ${{ secrets.GCP_SA_KEY }}

  notify-maintainers:
    needs: collect-reports
    uses: ./.github/workflows/notify-maintainers.yml

  update-report:
    needs: notify-maintainers
    uses: ./.github/workflows/update-report.yml


