name: Check Changed Directories and Trigger Sub-workflow

on: push

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      run_dataplex: ${{ steps.check.outputs.run_dataplex }}
      run_scenarios: ${{ steps.check.outputs.run_scenarios }}
      run_spark: ${{ steps.check.outputs.run_spark }}
      run_spark_dataproc: ${{ steps.check.outputs.run_spark_dataproc }}
      needs_subworkflows: ${{ steps.check.outputs.needs_subworkflows }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: check
        run: |
          # Initialize outputs
          echo "run_dataplex=false" >> $GITHUB_ENV
          echo "run_scenarios=false" >> $GITHUB_ENV
          echo "run_spark=false" >> $GITHUB_ENV
          echo "run_spark_dataproc=false" >> $GITHUB_ENV

          needs_subworkflows=()

          # Check if files have changed in each directory
          if git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep -q '^1/'; then
            echo "run_dataplex=true" >> $GITHUB_ENV
          fi
          if git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep -q '^2/'; then
            echo "run_scenarios=true" >> $GITHUB_ENV
          fi
          if git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep -q '^3/'; then
            echo "run_spark=true" >> $GITHUB_ENV
          fi
          if git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep -q '^4/'; then
            echo "run_spark_dataproc=true" >> $GITHUB_ENV
          fi

  dataplex:
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.run_dataplex == 'true' }}
    uses: ./.github/workflows/consumer-dataplex.yml

  scenarios:
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.run_scenarios == 'true' }}
    uses: ./.github/workflows/consumer-scenarios.yml

  spark:
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.run_spark == 'true' }}
    uses: ./.github/workflows/producer-spark.yml

  spark-dataproc:
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.run_spark_dataproc == 'true' }}
    uses: ./.github/workflows/producer-spark-dataproc.yml

  collect-reports:
    needs:
      - dataplex
      - scenarios
      - spark
      - dataproc
    if: ${{ always() }}
    uses: ./.github/workflows/collect-reports.yml
