name: Update repo files
# TODO update from placeholder to actual functionality
on:
  workflow_call:
    secrets:
      gcpKey:
        required: true
    inputs:
      exec_time:
        type: string
        description: "Workflow execution time"

jobs:
  update-repo-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create report.json directory
        run: mkdir -p reports/

      - uses: actions/download-artifact@v4
        with:
          path: reports/
          merge-multiple: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: |
            generated-files/report.json
            generated-files/versions.json
          branch: "test-${{ inputs.exec_time }}"
          title: "[bot] update report with data from run ${{ github.run_id }} executed ${{ inputs.exec_time }}"
