name: Update repo files
on:
  workflow_call:

permissions:
  id-token: write
  contents: write  # Add any other permissions as needed
  pull-requests: write
  issues: write

jobs:
  update-repository-files:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: refs/heads/main

      - name: Create report.json directory
        run: mkdir -p reports/

      - uses: actions/download-artifact@v4
        with:
          pattern: updated-*
          path: generated-files/
          merge-multiple: true

      - id: replace-modified-files
        name: Replace Modified Files
        run: |
          mv ./generated-files/updated-report.json ./generated-files/report.json || echo "updated-report.json no found"
          mv ./generated-files/updated_releases.json ./generated-files/releases.json || echo "updated_releases.json no found"
          mv ./generated-files/updated_spec_versions.json ./generated-files/spec_versions.json || echo "updated_spec_versions.json no found"
          mv ./generated-files/updated-compatibility-table.md ./generated-files/compatibility-table.md || echo "updated-compatibility-table.md no found"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: |
            generated-files/report.json
            generated-files/releases.json
            generated-files/spec_versions.json
            generated-files/compatibility-table.md
          branch: "test-${{ github.run_id }}"
          title: "[bot] update report with data from run ${{ github.run_id }}"
