name: Update repo files
# TODO update from placeholder to actual functionality
on:
  workflow_call:
    inputs:
      exec_time:
        type: string
        description: "Workflow execution time"

permissions:
  id-token: write
  contents: write  # Add any other permissions as needed
  pull-requests: write

jobs:
  update-repo-files:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: refs/heads/main

      - name: Create report.json directory
        run: mkdir -p reports/

      - uses: actions/download-artifact@v4
        with:
          pattern: updated-*
          path: generated-files/
          merge-multiple: true

      - id: replace-modified-files
        name: Replace Modified Files
        run: |
          if [ -f ./generated-files/updated-report.json ]; 
          then 
            mv ./generated-files/updated-report.json ./generated-files/report.json
          else
            echo "./generated-files/updated-report.json does not exist"
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: |
            generated-files/report.json
          branch: "test-${{ inputs.exec_time }}"
          title: "[bot] update report with data from run ${{ github.run_id }} executed ${{ inputs.exec_time }}"
