name: Update website with compatibility data

on:
  workflow_call:
    secrets:
      CI_PUSH_TOKEN:
        required: true
    
jobs:
  update-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/upload-artifact@v4
        with:
          name: update-website-script
          path: scripts/update_website_files.sh
          retention-days: 1

      - name: get website fork
        uses: actions/checkout@v4
        with:
          repository: tnazarew/openlineage-site
          ref: refs/heads/main
          token: ${{ secrets.CI_PUSH_TOKEN }}

      - uses: actions/download-artifact@v4
        with:
          name: updated-compatibility-tables
          path: updated-compatibility-tables
          merge-multiple: true

      - uses: actions/download-artifact@v4
        with:
          name: update-website-script
          path: update_website_files.sh
          merge-multiple: true

      - name: Install dependencies
        run: ./update_website_files.sh

      - name: Configure Git
        run: |
          git config user.name "compatibility-tests-gha[bot]"
          git config user.email "compatibility-tests-gha[bot]@users.noreply.github.com"

      - name: Push changes
        id: push-changes
        # env:
        #   TOKEN: ${{ secrets.CI_PUSH_TOKEN }}
        run: |
          git add -u
          git commit -sm "[bot] update compatibility tables with run data"
          # git remote set-url origin https://x-access-token:${TOKEN}@github.com/tnazarew/openlineage-site.git
          git push origin main